//! Regenerates `regions/tests/regioncode-vectors.json`.
//!
//! The Python builder derives radio-facing region codes independently of this
//! workspace, and a subtly different ARNCE table or hash transform there would
//! produce a database whose codes disagree with every radio. Rather than trust
//! two implementations to match, both compute the same exhaustive table and
//! compare one digest over it: all 47,988 short codes of one to three ASCII
//! alphanumerics, plus a set of named regions covering the transform's three
//! blocks and its pass-through case.
//!
//! Run with `cargo run -p umsh-regiondb --example gen_region_vectors`.

use std::fmt::Write as _;

use umsh_core::RegionCode;

/// Short-code input alphabet, in the order the digest walks it.
const ALPHABET: &[u8] = b"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ";

/// Named regions worth pinning individually: two from the spec's own table,
/// one that lands in each of the transform's three blocks, and one whose hash
/// needs no transform at all.
const NAMES: &[&str] = &[
    "Rogue Valley",
    "Willamette Valley",
    "East Bay",
    "Wasatch Front",
    "SF Bay Area",
    "Southern Oregon",
    "Ashland",
    "Puget Sound",
    "Front Range",
    "Central Valley",
    "rogue valley",
    "ROGUE VALLEY",
];

fn short_codes() -> Vec<String> {
    let mut out = Vec::with_capacity(36 + 36 * 36 + 36 * 36 * 36);
    for &a in ALPHABET {
        out.push(String::from_utf8(vec![a]).unwrap());
        for &b in ALPHABET {
            out.push(String::from_utf8(vec![a, b]).unwrap());
            for &c in ALPHABET {
                out.push(String::from_utf8(vec![a, b, c]).unwrap());
            }
        }
    }
    out
}

fn main() {
    let mut table = String::new();
    let mut count = 0usize;
    for code in short_codes() {
        let value = RegionCode::from_short_code(&code)
            .unwrap_or_else(|err| panic!("short code {code} rejected: {err}"));
        writeln!(table, "{code}={:04X}", value.as_u16()).unwrap();
        count += 1;
    }
    let digest = sha256_hex(table.as_bytes());

    let mut json = String::new();
    json.push_str("{\n");
    json.push_str("  \"comment\": \"Generated by `cargo run -p umsh-regiondb --example gen_region_vectors`. Do not hand-edit.\",\n");
    json.push_str(&format!(
        "  \"short_code_alphabet\": \"{}\",\n",
        std::str::from_utf8(ALPHABET).unwrap()
    ));
    json.push_str(&format!("  \"short_code_count\": {count},\n"));
    json.push_str(&format!("  \"short_code_digest\": \"{digest}\",\n"));
    json.push_str("  \"short_codes\": {\n");
    let samples = [
        "SJC", "MFR", "US", "WA", "SFO", "SQL", "OAK", "PAO", "CA", "OR", "IN", "A", "Z", "W7",
        "5X2", "0", "999", "A0", "0A",
    ];
    for (index, code) in samples.iter().enumerate() {
        let value = RegionCode::from_short_code(code).unwrap();
        let comma = if index + 1 == samples.len() { "" } else { "," };
        json.push_str(&format!("    \"{code}\": {}{comma}\n", value.as_u16()));
    }
    json.push_str("  },\n");
    json.push_str("  \"names\": {\n");
    for (index, name) in NAMES.iter().enumerate() {
        let value = RegionCode::from_name(name);
        let comma = if index + 1 == NAMES.len() { "" } else { "," };
        json.push_str(&format!("    \"{name}\": {}{comma}\n", value.as_u16()));
    }
    json.push_str("  }\n");
    json.push_str("}\n");

    print!("{json}");
}

fn sha256_hex(data: &[u8]) -> String {
    use sha2::{Digest, Sha256};

    let mut out = String::with_capacity(64);
    for byte in Sha256::digest(data) {
        write!(out, "{byte:02x}").unwrap();
    }
    out
}
