//! Cross-implementation conformance.
//!
//! Every fixture read here is committed under `regions/tests/` and generated by
//! the Python builder. If this crate and that builder ever disagree about a
//! position, a region code, or a geometry blob, one of them is producing
//! configuration that does not match what a radio would do with it — so the
//! disagreement is the failure, whichever side is "right".
//!
//! These tests only ever read the committed fixture database. Building one
//! belongs to `make regions-build-fixture`, not to `cargo test`.

use std::path::{Path, PathBuf};

use serde_json::Value;
use umsh_core::RegionCode;
use umsh_regiondb::{Membership, RegionDb, blob};

fn regions_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .and_then(Path::parent)
        .expect("crate lives two levels below the repository root")
        .join("regions")
}

fn fixture_database() -> RegionDb {
    let path = regions_dir().join("tests/fixture/fixture.regiondb");
    RegionDb::open(&path).unwrap_or_else(|error| {
        panic!(
            "cannot open the committed fixture database at {}: {error}. \
             It is a build output; regenerate it with `make regions-build-fixture`.",
            path.display()
        )
    })
}

fn read_json(relative: &str) -> Value {
    let path = regions_dir().join(relative);
    let text = std::fs::read_to_string(&path)
        .unwrap_or_else(|error| panic!("cannot read {}: {error}", path.display()));
    serde_json::from_str(&text).expect("fixture is valid JSON")
}

#[test]
fn opens_the_fixture_and_reports_its_version() {
    let database = fixture_database();
    assert_eq!(database.format_version(), umsh_regiondb::FORMAT_VERSION);
    assert_eq!(database.dataset_version(), "fixture-1");
    assert!(database.region_count() > 0);
    assert!(database.metadata().contains_key("content_hash"));
}

#[test]
fn rejects_a_newer_format_version() {
    // A future release may add tables this build cannot interpret. Reading it
    // anyway would produce a plausible-looking but wrong region list, which is
    // worse than refusing.
    let temporary = std::env::temp_dir().join("umsh-regiondb-future-format.regiondb");
    let _ = std::fs::remove_file(&temporary);
    std::fs::copy(
        regions_dir().join("tests/fixture/fixture.regiondb"),
        &temporary,
    )
    .expect("copy fixture");
    {
        let connection = rusqlite::Connection::open(&temporary).expect("open copy");
        connection
            .pragma_update(None, "user_version", umsh_regiondb::FORMAT_VERSION + 1)
            .expect("bump version");
    }
    match RegionDb::open(&temporary) {
        Err(umsh_regiondb::RegionDbError::UnsupportedFormat { found, supported }) => {
            assert_eq!(found, umsh_regiondb::FORMAT_VERSION + 1);
            assert_eq!(supported, umsh_regiondb::FORMAT_VERSION);
        }
        Err(other) => panic!("unexpected error: {other}"),
        Ok(_) => panic!("a newer format version must be refused"),
    }
    let _ = std::fs::remove_file(&temporary);
}

#[test]
fn geometry_blobs_match_the_golden_vectors() {
    let golden = read_json("tests/geometry-golden.json");
    assert_eq!(golden["geometry_format_version"], 1);

    for case in golden["cases"].as_array().expect("cases array") {
        let name = case["name"].as_str().unwrap();
        let bytes = hex_to_bytes(case["blob_hex"].as_str().unwrap());
        let rings = blob::decode(&bytes).unwrap_or_else(|e| panic!("{name}: {e}"));

        let expected = case["rings"].as_array().unwrap();
        assert_eq!(rings.len(), expected.len(), "{name}: ring count");
        for (ring, want) in rings.iter().zip(expected) {
            assert_eq!(
                i64::from(ring.role),
                want["role"].as_i64().unwrap(),
                "{name}"
            );
            let points: Vec<(i32, i32)> = want["points"]
                .as_array()
                .unwrap()
                .iter()
                .map(|point| {
                    let pair = point.as_array().unwrap();
                    (
                        pair[0].as_i64().unwrap() as i32,
                        pair[1].as_i64().unwrap() as i32,
                    )
                })
                .collect();
            assert_eq!(ring.points, points, "{name}: vertices");
        }

        for probe in case["probes"].as_array().unwrap() {
            let inside = blob::point_in_rings(
                &rings,
                probe["lon_e6"].as_i64().unwrap() as i32,
                probe["lat_e6"].as_i64().unwrap() as i32,
            );
            assert_eq!(
                inside,
                probe["inside"].as_bool().unwrap(),
                "{name}: probe {probe}"
            );
        }
    }
}

#[test]
fn region_codes_match_the_canonical_table() {
    let vectors = read_json("tests/regioncode-vectors.json");
    for (code, expected) in vectors["short_codes"].as_object().unwrap() {
        let actual = RegionCode::from_short_code(code).expect("short code encodes");
        assert_eq!(
            i64::from(actual.as_u16()),
            expected.as_i64().unwrap(),
            "short code {code}"
        );
    }
    for (name, expected) in vectors["names"].as_object().unwrap() {
        assert_eq!(
            i64::from(RegionCode::from_name(name).as_u16()),
            expected.as_i64().unwrap(),
            "name {name}"
        );
    }
}

#[test]
fn conformance_cases_replay_exactly() {
    let database = fixture_database();
    let fixture = read_json("tests/conformance.json");
    assert_eq!(
        fixture["dataset_version"].as_str().unwrap(),
        database.dataset_version(),
        "the conformance fixture was generated from a different database"
    );

    let cases = fixture["cases"].as_array().expect("cases array");
    assert!(!cases.is_empty());

    for case in cases {
        let latitude = case["lat"].as_f64().unwrap();
        let longitude = case["lon"].as_f64().unwrap();
        let result = database
            .lookup_detailed(latitude, longitude)
            .unwrap_or_else(|error| panic!("{latitude},{longitude}: {error}"));

        let keys: Vec<&str> = result
            .matches
            .iter()
            .map(|entry| entry.region_key.as_str())
            .collect();
        let expected_keys: Vec<&str> = case["region_keys"]
            .as_array()
            .unwrap()
            .iter()
            .map(|value| value.as_str().unwrap())
            .collect();
        assert_eq!(keys, expected_keys, "matches at {latitude},{longitude}");

        let memberships: Vec<&str> = result
            .matches
            .iter()
            .map(|entry| match entry.membership {
                Membership::Core => "core",
                Membership::Expanded => "expanded",
            })
            .collect();
        let expected_memberships: Vec<&str> = case["memberships"]
            .as_array()
            .unwrap()
            .iter()
            .map(|value| value.as_str().unwrap())
            .collect();
        assert_eq!(
            memberships, expected_memberships,
            "membership at {latitude},{longitude}"
        );

        let names: Vec<&str> = result
            .radio_regions
            .iter()
            .map(|region| region.name.as_str())
            .collect();
        let expected_names: Vec<&str> = case["radio_names"]
            .as_array()
            .unwrap()
            .iter()
            .map(|value| value.as_str().unwrap())
            .collect();
        assert_eq!(
            names, expected_names,
            "radio names at {latitude},{longitude}"
        );

        let codes: Vec<i64> = result
            .radio_regions
            .iter()
            .map(|region| i64::from(region.code.as_u16()))
            .collect();
        let expected_codes: Vec<i64> = case["wire_codes"]
            .as_array()
            .unwrap()
            .iter()
            .map(|value| value.as_i64().unwrap())
            .collect();
        assert_eq!(
            codes, expected_codes,
            "wire codes at {latitude},{longitude}"
        );

        let default = result
            .suggested_default_region
            .as_ref()
            .map(|region| i64::from(region.code.as_u16()));
        assert_eq!(
            default,
            case["default_wire_code"].as_i64(),
            "suggested default at {latitude},{longitude}"
        );
    }
}

#[test]
fn the_lookup_cache_agrees_with_exact_geometry() {
    let database = fixture_database();
    let fixture = read_json("tests/conformance.json");
    for case in fixture["cases"].as_array().unwrap() {
        let latitude = case["lat"].as_f64().unwrap();
        let longitude = case["lon"].as_f64().unwrap();
        let cached = database.lookup_detailed(latitude, longitude).unwrap();
        let exact = database.lookup_exhaustive(latitude, longitude).unwrap();
        assert_eq!(
            cached.matches, exact.matches,
            "cache disagreed with exact geometry at {latitude},{longitude}"
        );
    }
}

#[test]
fn san_carlos_is_a_location_but_not_a_commercial_airport() {
    // The standing regression. Upstream marks San Carlos as having scheduled
    // service; nobody there would call it their airport, and the two layers
    // exist precisely so the database can say both things at once.
    let database = fixture_database();
    let result = database.lookup_detailed(37.5119, -122.2495).unwrap();
    let keys: Vec<&str> = result
        .matches
        .iter()
        .map(|entry| entry.region_key.as_str())
        .collect();
    assert!(keys.contains(&"iata-location:SQL"), "{keys:?}");
    assert!(!keys.contains(&"iata-airport:SQL"), "{keys:?}");
    assert_eq!(
        result.suggested_default_region.map(|region| region.name),
        Some("SFO".to_owned())
    );
}

#[test]
fn one_radio_region_per_code_even_when_several_layers_match() {
    let database = fixture_database();
    let result = database.lookup_detailed(37.6189, -122.3750).unwrap();
    let semantic = result
        .matches
        .iter()
        .filter(|entry| entry.radio_name == "SFO")
        .count();
    let radio = result
        .radio_regions
        .iter()
        .filter(|region| region.name == "SFO")
        .count();
    assert!(semantic > 1, "expected several SFO senses, got {semantic}");
    assert_eq!(radio, 1);
}

#[test]
fn a_position_with_no_coverage_returns_nothing() {
    let database = fixture_database();
    let result = database.lookup_codes(10.0, -150.0).unwrap();
    assert!(result.radio_regions.is_empty());
    assert!(result.suggested_default_region.is_none());
}

#[test]
fn lookup_codes_skips_the_semantic_detail() {
    let database = fixture_database();
    let brief = database.lookup_codes(37.5119, -122.2495).unwrap();
    let detailed = database.lookup_detailed(37.5119, -122.2495).unwrap();
    assert!(brief.matches.is_empty());
    assert!(!detailed.matches.is_empty());
    assert_eq!(brief.radio_regions, detailed.radio_regions);
}

#[test]
fn rejects_positions_that_are_not_on_the_globe() {
    let database = fixture_database();
    for (latitude, longitude) in [
        (91.0, 0.0),
        (-91.0, 0.0),
        (f64::NAN, 0.0),
        (0.0, f64::INFINITY),
    ] {
        assert!(
            database.lookup_codes(latitude, longitude).is_err(),
            "{latitude},{longitude} should not be a usable position"
        );
    }
}

#[test]
fn the_antimeridian_names_one_meridian() {
    let database = fixture_database();
    let east = database.lookup_codes(0.0, 180.0).unwrap();
    let west = database.lookup_codes(0.0, -180.0).unwrap();
    assert_eq!(east.radio_regions, west.radio_regions);
}

fn hex_to_bytes(text: &str) -> Vec<u8> {
    (0..text.len())
        .step_by(2)
        .map(|index| u8::from_str_radix(&text[index..index + 2], 16).expect("hex"))
        .collect()
}
