"""The cross-implementation fixture.

Every implementation that answers a lookup — this builder, the Rust runtime,
the mobile facade, and eventually the browser — replays the same file and must
agree exactly. Generating it from the compiled database rather than from the
compiler's in-memory geometry is deliberate: what the implementations share is
the file, so that is what the fixture is taken over.
"""

from __future__ import annotations

import json
import random
from pathlib import Path

import yaml

from .lookup import RegionDb


def generate(
    database: Path,
    output: Path,
    *,
    points: Path | None = None,
    sample: int = 0,
    seed: int = 20260821,
) -> int:
    cases = []
    with RegionDb(database) as db:
        positions: list[tuple[float, float]] = []
        if points:
            document = yaml.safe_load(points.read_text()) or {}
            positions.extend((case["lat"], case["lon"]) for case in document.get("points", []))
        if sample:
            from .validate import _boundary_positions, _uniform_positions

            generator = random.Random(seed)
            positions.extend(_uniform_positions(generator, sample // 2))
            positions.extend(_boundary_positions(db, generator, sample - sample // 2))

        for latitude, longitude in positions:
            result = db.lookup(latitude, longitude)
            cases.append(
                {
                    "lat": round(latitude, 9),
                    "lon": round(longitude, 9),
                    "region_keys": [match.region_key for match in result.matches],
                    "memberships": [
                        "core" if match.membership == 0 else "expanded" for match in result.matches
                    ],
                    "radio_names": [item.name for item in result.radio_regions],
                    "wire_codes": [item.code for item in result.radio_regions],
                    "default_wire_code": (
                        result.suggested_default_region.code
                        if result.suggested_default_region
                        else None
                    ),
                }
            )
        dataset_version = db.dataset_version

    document = {
        "comment": (
            "Generated by `regiondb-build gen-conformance`. Every implementation that reads "
            "a .regiondb must reproduce these results exactly."
        ),
        "dataset_version": dataset_version,
        "database": database.name,
        "cases": cases,
    }
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(json.dumps(document, indent=2) + "\n")
    return len(cases)
