"""Distilling vendor data into committed extracts.

`update` is the only command that reads `regions/vendor/`, and what it writes
is the build's actual input: small, sorted, canonically formatted files that go
into the repository. A data refresh then lands as an ordinary pull request
whose diff is the geographic change, reviewed like any other.

The pass is idempotent by construction — same vendor bytes, same output bytes —
so `update --check` can prove that the committed extracts are exactly what the
pinned sources produce, and that nobody hand-edited them. Manual corrections
belong in `classifications/` and `overrides/`, which the build applies on top.

Not every layer is committed. The point and attribute datasets are, because
they are small and genuinely reviewable. Global country boundaries are not:
even simplified to 500 m they are about 30 MB of GeoJSON, which no reviewer
reads and no repository should carry per release. Those stay on the fetch path
and are written into `regions/build/`, which is ignored. US state boundaries
are small enough to commit and are.
"""

from __future__ import annotations

import csv
import io
import json
import math
from dataclasses import dataclass, field
from pathlib import Path

from pyogrio.raw import read as read_ogr
from shapely import from_wkb

from . import geom
from .fetch import load_lock
from .sourcetree import (
    COMMERCIAL_CANDIDATE_COLUMNS,
    IATA_LOCATIONS_COLUMNS,
    METRO_CODE_COLUMNS,
)

# Precision the boundary extracts are written at. This is the finest a build
# can be: `build` may simplify further under policy, never less. It is stated
# here rather than read from policy so that changing a build tolerance never
# requires vendor data to regenerate an extract.
BOUNDARY_EXTRACT_TOLERANCE_M = 50.0
BOUNDARY_COORDINATE_DIGITS = 6

# Facility types that never carry a meaningful position for routing.
EXCLUDED_AIRPORT_TYPES = {"closed"}

# State FIPS codes at or above this are territories rather than states. Policy
# excludes them from V1; see `regions/policy.yaml`.
TERRITORY_FIPS_FLOOR = 60


class ExtractError(ValueError):
    """Vendor data cannot be distilled as configured."""


@dataclass
class UpdateResult:
    report: list[str] = field(default_factory=list)
    differences: list[str] = field(default_factory=list)


def _provenance_header(source_id: str, lock: dict) -> str:
    entry = lock.get("sources", {}).get(source_id, {})
    return "\n".join(
        [
            "# Generated by `regiondb-build update`. Do not hand-edit: the next update",
            "# pass overwrites this file. Corrections belong in classifications/ or",
            "# overrides/, which the build applies on top.",
            f"# source: {source_id}",
            f"# url: {entry.get('url', 'unknown')}",
            f"# sha256: {entry.get('sha256', 'unknown')}",
            f"# retrieved: {entry.get('retrieved_at', 'unknown')}",
        ]
    )


def _write(path: Path, text: str, result: UpdateResult, check: bool) -> None:
    """Write an extract, or in check mode compare against what is committed."""
    if check:
        existing = path.read_text() if path.exists() else None
        if existing != text:
            result.differences.append(str(path))
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text)


def _csv_text(header: str, columns: list[str], rows: list[dict[str, str]]) -> str:
    buffer = io.StringIO()
    buffer.write(header + "\n")
    writer = csv.DictWriter(buffer, fieldnames=columns, lineterminator="\n")
    writer.writeheader()
    writer.writerows(rows)
    return buffer.getvalue()


def _coordinate(value: str) -> float:
    number = float(value)
    if not math.isfinite(number):
        raise ExtractError(f"coordinate {value!r} is not finite")
    return number


def _format_coordinate(value: float) -> str:
    """Fixed formatting, so an unchanged coordinate never churns the diff."""
    return f"{value:.6f}"


def airports(
    vendor: Path, lock: dict
) -> tuple[list[dict[str, str]], list[dict[str, str]], list[str]]:
    """Normalize OurAirports into positioned IATA sites and commercial candidates."""
    notes: list[str] = []
    rows = list(csv.DictReader((vendor / "airports.csv").read_text().splitlines()))

    by_iata: dict[str, dict[str, str]] = {}
    conflicts: list[str] = []
    for row in rows:
        iata = (row.get("iata_code") or "").strip().upper()
        if len(iata) != 3 or not iata.isascii() or not iata.isalpha():
            continue
        kind = (row.get("type") or "").strip()
        if kind in EXCLUDED_AIRPORT_TYPES:
            continue
        try:
            latitude = _coordinate(row["latitude_deg"])
            longitude = _coordinate(row["longitude_deg"])
        except (KeyError, ValueError):
            notes.append(f"{iata}: unusable coordinates, dropped")
            continue
        if not -90.0 <= latitude <= 90.0:
            notes.append(f"{iata}: latitude {latitude} out of range, dropped")
            continue
        longitude = ((longitude + 180.0) % 360.0) - 180.0

        record = {
            "iata": iata,
            "ident": (row.get("ident") or "").strip(),
            "type": kind,
            "name": " ".join((row.get("name") or "").split()),
            "latitude_deg": _format_coordinate(latitude),
            "longitude_deg": _format_coordinate(longitude),
            "iso_country": (row.get("iso_country") or "").strip().upper(),
            "iso_region": (row.get("iso_region") or "").strip().upper(),
            "municipality": " ".join((row.get("municipality") or "").split()),
            "scheduled_service": (
                "yes" if (row.get("scheduled_service") or "").strip() == "yes" else "no"
            ),
        }

        if iata in by_iata:
            previous = by_iata[iata]
            if (
                previous["latitude_deg"] == record["latitude_deg"]
                and previous["longitude_deg"] == record["longitude_deg"]
            ):
                continue
            # Never silently keep the first: whichever wins changes a routing
            # boundary, and the choice has to be someone's decision.
            conflicts.append(
                f"{iata}: {previous['ident']} at "
                f"{previous['latitude_deg']},{previous['longitude_deg']} and "
                f"{record['ident']} at {record['latitude_deg']},{record['longitude_deg']}"
            )
            continue
        by_iata[iata] = record

    if conflicts:
        raise ExtractError(
            "upstream carries the same IATA code at conflicting positions:\n  "
            + "\n  ".join(sorted(conflicts))
            + "\nResolve each one with an explicit override before updating."
        )

    sites = [by_iata[iata] for iata in sorted(by_iata)]
    candidates = [
        {column: site[column] for column in COMMERCIAL_CANDIDATE_COLUMNS}
        for site in sites
        if site["scheduled_service"] == "yes"
    ]
    notes.append(f"{len(sites)} positioned IATA sites, {len(candidates)} commercial candidates")
    return sites, candidates, notes


def metro_codes(vendor: Path) -> list[dict[str, str]]:
    """Seed list of metropolitan IATA codes.

    Only the codes and their names are taken. The coordinates in this file are
    city center points, and a metro region is a containment polygon that has to
    be drawn and reviewed by a person.
    """
    rows = list(csv.DictReader((vendor / "citycodes.csv").read_text().splitlines()))
    seen: dict[str, dict[str, str]] = {}
    for row in rows:
        code = (row.get("code") or row.get("city_code") or "").strip().upper()
        if len(code) != 3 or not code.isalpha():
            continue
        seen[code] = {
            "iata": code,
            "name": " ".join((row.get("name") or row.get("city") or "").split()),
            "iso_country": (row.get("country_code") or row.get("country") or "").strip().upper(),
        }
    return [seen[code] for code in sorted(seen)]


def iso3_to_iso2(vendor: Path) -> dict[str, str]:
    rows = list(csv.DictReader((vendor / "country-codes.csv").read_text().splitlines()))
    mapping = {}
    for row in rows:
        alpha3 = (row.get("ISO3166-1-Alpha-3") or "").strip().upper()
        alpha2 = (row.get("ISO3166-1-Alpha-2") or "").strip().upper()
        if len(alpha3) == 3 and len(alpha2) == 2:
            mapping[alpha3] = alpha2
    return mapping


def _boundary_document(geometry, name: str, feature_id: str) -> str:
    simplified = geom.simplify_m(geom.normalize(geometry, name=name), BOUNDARY_EXTRACT_TOLERANCE_M)
    mapping = simplified.__geo_interface__
    rounded = json.loads(
        json.dumps(mapping),
        parse_float=lambda value: round(float(value), BOUNDARY_COORDINATE_DIGITS),
    )
    document = {
        "type": "Feature",
        "properties": {"name": name, "source_feature_id": feature_id},
        "geometry": rounded,
    }
    return json.dumps(document, sort_keys=True, separators=(",", ":")) + "\n"


def countries(vendor: Path, destination: Path, mapping: dict[str, str]) -> list[str]:
    """Write country boundaries, keyed by ISO 3166-1 alpha-2."""
    notes: list[str] = []
    meta, _, geometry, fields = read_ogr(str(vendor / "geoBoundariesCGAZ_ADM0.gpkg"))
    names = list(meta["fields"])
    groups = fields[names.index("shapeGroup")]
    labels = fields[names.index("shapeName")]

    destination.mkdir(parents=True, exist_ok=True)
    written = 0
    for wkb, alpha3, label in zip(geometry, groups, labels, strict=True):
        code = mapping.get(str(alpha3).upper())
        if not code:
            notes.append(f"{alpha3} ({label}) has no ISO 3166-1 alpha-2 code and was skipped")
            continue
        (destination / f"{code}.geojson").write_text(
            _boundary_document(from_wkb(wkb), str(label), str(alpha3))
        )
        written += 1
    notes.append(f"{written} country boundaries written to {destination}")
    return notes


def us_states(vendor: Path, destination: Path, result: UpdateResult, check: bool) -> list[str]:
    """Write the 50 states plus the District of Columbia, keyed by USPS code."""
    archive = vendor / "tl_2024_us_state.zip"
    meta, _, geometry, fields = read_ogr(f"/vsizip/{archive}")
    names = list(meta["fields"])
    codes = fields[names.index("STUSPS")]
    fips = fields[names.index("GEOID")]
    labels = fields[names.index("NAME")]

    kept = 0
    skipped = []
    for wkb, code, geoid, label in zip(geometry, codes, fips, labels, strict=True):
        if int(geoid) >= TERRITORY_FIPS_FLOOR:
            skipped.append(str(code))
            continue
        _write(
            destination / f"{str(code).upper()}.geojson",
            _boundary_document(from_wkb(wkb), str(label), f"fips:{geoid}"),
            result,
            check,
        )
        kept += 1
    return [
        f"{kept} US state boundaries; territories excluded by policy: "
        + (", ".join(sorted(skipped)) or "none")
    ]


def update(root: Path, *, check: bool = False) -> UpdateResult:
    """Run the whole distillation pass."""
    vendor = root / "vendor"
    if not vendor.is_dir():
        raise ExtractError(
            f"{vendor} does not exist. Run `regiondb-build fetch` first: `update` reads the "
            "downloaded sources, and only `fetch` may touch the network."
        )
    lock = load_lock(root / "upstream" / "lock.json")
    extracts = root / "extracts"
    result = UpdateResult()

    sites, candidates, notes = airports(vendor, lock)
    result.report.extend(notes)
    header = _provenance_header("ourairports-airports", lock)
    _write(
        extracts / "iata-locations.csv",
        _csv_text(header, IATA_LOCATIONS_COLUMNS, sites),
        result,
        check,
    )
    _write(
        extracts / "commercial-airport-candidates.csv",
        _csv_text(header, COMMERCIAL_CANDIDATE_COLUMNS, candidates),
        result,
        check,
    )

    metros = metro_codes(vendor)
    _write(
        extracts / "metro-codes.csv",
        _csv_text(_provenance_header("iata-city-codes", lock), METRO_CODE_COLUMNS, metros),
        result,
        check,
    )
    result.report.append(f"{len(metros)} metropolitan IATA codes seeded")

    result.report.extend(us_states(vendor, extracts / "boundaries" / "us-state", result, check))

    if not check:
        mapping = iso3_to_iso2(vendor)
        result.report.extend(countries(vendor, root / "build" / "boundaries" / "country", mapping))
        result.report.append(
            "country boundaries are not committed: even simplified they are tens of "
            "megabytes per release. They are written under regions/build/, which is "
            "ignored, and a world build needs `regiondb-build fetch` and `update` first."
        )

    return result
