"""Distilling vendor data into committed extracts.

`update` is the only command that reads `regions/vendor/`, and what it writes
is the build's actual input: small, sorted, canonically formatted files that go
into the repository. A data refresh then lands as an ordinary pull request
whose diff is the geographic change, reviewed like any other.

The pass is idempotent by construction — same vendor bytes, same output bytes —
so `update --check` can prove that the committed extracts are exactly what the
pinned sources produce, and that nobody hand-edited them. Manual corrections
belong in `classifications/` and `overrides/`, which the build applies on top.

Not every layer is committed. The point and attribute datasets are, because
they are small and genuinely reviewable. Global country boundaries are not:
even simplified to 500 m they are about 30 MB of GeoJSON, which no reviewer
reads and no repository should carry per release. Those stay on the fetch path
and are written into `regions/build/`, which is ignored. US state boundaries
are small enough to commit and are.
"""

from __future__ import annotations

import csv
import io
import json
import math
from dataclasses import dataclass, field
from pathlib import Path

from pyogrio.raw import read as read_ogr
from shapely import STRtree, from_wkb, unary_union
from shapely.geometry import MultiPolygon

from . import geom, policy
from .fetch import load_lock
from .sourcetree import (
    COMMERCIAL_CANDIDATE_COLUMNS,
    IATA_LOCATIONS_COLUMNS,
    METRO_CODE_COLUMNS,
)

# Precision the boundary extracts are written at. This is the finest a build
# can be: `build` may simplify further under policy, never less. It is stated
# here rather than read from policy so that changing a build tolerance never
# requires vendor data to regenerate an extract.
BOUNDARY_EXTRACT_TOLERANCE_M = 50.0

# Country regions are jurisdiction areas — land plus EEZ — whose edges are
# either legal constructs or 200-nautical-mile arcs. Nothing about them needs
# fifty-meter fidelity, and one kilometer keeps the whole committed layer
# under four megabytes.
COUNTRY_EXTRACT_TOLERANCE_M = 1000.0
BOUNDARY_COORDINATE_DIGITS = 6

# Facility types dropped from the database entirely. Closed facilities are
# gone from the world; heliports are excluded across the board for the time
# being — a helipad's IATA code names a rooftop, not an area anyone would
# configure a repeater for, and Manhattan alone carries three of them.
EXCLUDED_AIRPORT_TYPES = {"closed", "heliport", "balloonport"}

# Facility types eligible to be commercial-airport candidates. The commercial
# layer answers "which airport would a person here say they fly from", and a
# heliport or seaplane base is not an answer to that question even when a
# scheduled shuttle technically serves it — Manhattan's helipads all carry
# scheduled_service=yes upstream, and a database suggesting a helipad as the
# region default has misunderstood the question. Such facilities remain
# positioned IATA locations, which is the layer that means "nearby IATA-coded
# place".
COMMERCIAL_CANDIDATE_TYPES = {"small_airport", "medium_airport", "large_airport"}

# State FIPS codes at or above this are territories rather than states. Policy
# excludes them from V1; see `regions/policy.yaml`.
TERRITORY_FIPS_FLOOR = 60


class ExtractError(ValueError):
    """Vendor data cannot be distilled as configured."""


@dataclass
class UpdateResult:
    report: list[str] = field(default_factory=list)
    differences: list[str] = field(default_factory=list)


def _provenance_header(source_id: str, lock: dict) -> str:
    entry = lock.get("sources", {}).get(source_id, {})
    return "\n".join(
        [
            "# Generated by `regiondb-build update`. Do not hand-edit: the next update",
            "# pass overwrites this file. Corrections belong in classifications/ or",
            "# overrides/, which the build applies on top.",
            f"# source: {source_id}",
            f"# url: {entry.get('url', 'unknown')}",
            f"# sha256: {entry.get('sha256', 'unknown')}",
            f"# retrieved: {entry.get('retrieved_at', 'unknown')}",
        ]
    )


def _write(path: Path, text: str, result: UpdateResult, check: bool) -> None:
    """Write an extract, or in check mode compare against what is committed."""
    if check:
        existing = path.read_text() if path.exists() else None
        if existing != text:
            result.differences.append(str(path))
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text)


def _csv_text(header: str, columns: list[str], rows: list[dict[str, str]]) -> str:
    buffer = io.StringIO()
    buffer.write(header + "\n")
    writer = csv.DictWriter(buffer, fieldnames=columns, lineterminator="\n")
    writer.writeheader()
    writer.writerows(rows)
    return buffer.getvalue()


def _coordinate(value: str) -> float:
    number = float(value)
    if not math.isfinite(number):
        raise ExtractError(f"coordinate {value!r} is not finite")
    return number


def _format_coordinate(value: float) -> str:
    """Fixed formatting, so an unchanged coordinate never churns the diff."""
    return f"{value:.6f}"


def airports(
    vendor: Path, lock: dict
) -> tuple[list[dict[str, str]], list[dict[str, str]], list[str]]:
    """Normalize OurAirports into positioned IATA sites and commercial candidates."""
    notes: list[str] = []
    rows = list(csv.DictReader((vendor / "airports.csv").read_text().splitlines()))

    by_iata: dict[str, dict[str, str]] = {}
    conflicts: list[str] = []
    for row in rows:
        iata = (row.get("iata_code") or "").strip().upper()
        if len(iata) != 3 or not iata.isascii() or not iata.isalpha():
            continue
        kind = (row.get("type") or "").strip()
        if kind in EXCLUDED_AIRPORT_TYPES:
            continue
        try:
            latitude = _coordinate(row["latitude_deg"])
            longitude = _coordinate(row["longitude_deg"])
        except (KeyError, ValueError):
            notes.append(f"{iata}: unusable coordinates, dropped")
            continue
        if not -90.0 <= latitude <= 90.0:
            notes.append(f"{iata}: latitude {latitude} out of range, dropped")
            continue
        longitude = ((longitude + 180.0) % 360.0) - 180.0

        record = {
            "iata": iata,
            "ident": (row.get("ident") or "").strip(),
            "type": kind,
            "name": " ".join((row.get("name") or "").split()),
            "latitude_deg": _format_coordinate(latitude),
            "longitude_deg": _format_coordinate(longitude),
            "iso_country": (row.get("iso_country") or "").strip().upper(),
            "iso_region": (row.get("iso_region") or "").strip().upper(),
            "municipality": " ".join((row.get("municipality") or "").split()),
            "scheduled_service": (
                "yes" if (row.get("scheduled_service") or "").strip() == "yes" else "no"
            ),
        }

        if iata in by_iata:
            previous = by_iata[iata]
            if (
                previous["latitude_deg"] == record["latitude_deg"]
                and previous["longitude_deg"] == record["longitude_deg"]
            ):
                continue
            # Never silently keep the first: whichever wins changes a routing
            # boundary, and the choice has to be someone's decision.
            conflicts.append(
                f"{iata}: {previous['ident']} at "
                f"{previous['latitude_deg']},{previous['longitude_deg']} and "
                f"{record['ident']} at {record['latitude_deg']},{record['longitude_deg']}"
            )
            continue
        by_iata[iata] = record

    if conflicts:
        raise ExtractError(
            "upstream carries the same IATA code at conflicting positions:\n  "
            + "\n  ".join(sorted(conflicts))
            + "\nResolve each one with an explicit override before updating."
        )

    sites = [by_iata[iata] for iata in sorted(by_iata)]
    candidates = [
        {column: site[column] for column in COMMERCIAL_CANDIDATE_COLUMNS}
        for site in sites
        if site["scheduled_service"] == "yes" and site["type"] in COMMERCIAL_CANDIDATE_TYPES
    ]
    notes.append(f"{len(sites)} positioned IATA sites, {len(candidates)} commercial candidates")
    return sites, candidates, notes


def metro_codes(vendor: Path) -> list[dict[str, str]]:
    """Seed list of metropolitan IATA codes.

    Only the codes and their names are taken. The coordinates in this file are
    city center points, and a metro region is a containment polygon that has to
    be drawn and reviewed by a person.
    """
    rows = list(csv.DictReader((vendor / "citycodes.csv").read_text().splitlines()))
    seen: dict[str, dict[str, str]] = {}
    for row in rows:
        code = (row.get("code") or row.get("city_code") or "").strip().upper()
        if len(code) != 3 or not code.isalpha():
            continue
        seen[code] = {
            "iata": code,
            "name": " ".join((row.get("name") or row.get("city") or "").split()),
            "iso_country": (row.get("country_code") or row.get("country") or "").strip().upper(),
        }
    return [seen[code] for code in sorted(seen)]


def iso3_to_iso2(vendor: Path) -> dict[str, str]:
    rows = list(csv.DictReader((vendor / "country-codes.csv").read_text().splitlines()))
    mapping = {}
    for row in rows:
        alpha3 = (row.get("ISO3166-1-Alpha-3") or "").strip().upper()
        alpha2 = (row.get("ISO3166-1-Alpha-2") or "").strip().upper()
        if len(alpha3) == 3 and len(alpha2) == 2:
            mapping[alpha3] = alpha2
    return mapping


def _charted_land(vendor: Path) -> STRtree:
    """The world's land at Natural Earth 50m scale, indexed for clipping.

    This is the physical layer with no idea of countries; jurisdiction comes
    from intersecting it with each country's EEZ + land union. 50m misses the
    smallest islets, which costs those islets their water reach — the report
    names any country left without charted land entirely, and that country
    keeps its whole jurisdiction rather than vanishing.
    """
    _, _, geometry, _ = read_ogr(f"/vsizip/{vendor / 'ne_50m_land.zip'}")
    parts = []
    for wkb in geometry:
        parts.extend(geom.polygonal(from_wkb(wkb)).geoms)
    return STRtree(parts)


def _land_within(land: STRtree, jurisdiction) -> MultiPolygon:
    """The charted land inside one jurisdiction area."""
    candidates = [land.geometries[i] for i in land.query(jurisdiction, predicate="intersects")]
    if not candidates:
        return MultiPolygon([])
    return geom.polygonal(jurisdiction.intersection(unary_union(candidates)))


def _water_reach(land_area, ceiling, reach_m: float) -> MultiPolygon:
    """Land plus its water, out to `reach_m` but never past `ceiling`.

    The ceiling is what keeps the buffer politically neutral: a country's is
    its EEZ + land union, whose bilateral maritime lines already divide the
    water between neighbors, so growing toward a neighbor stops exactly where
    the law does. Buffering is done on land simplified to a kilometer — the
    outline of a 100 km buffer cannot remember 50 m coastline detail anyway —
    and the land itself is unioned back so the coastline stays interior.
    """
    slimmed = geom.polygonal(geom.simplify_m(land_area, 1000.0))
    if slimmed.is_empty:
        slimmed = land_area
    grown = geom.buffer_m(slimmed, reach_m)
    return geom.polygonal(unary_union([land_area, grown.intersection(ceiling)]))


def _boundary_document(
    geometry, name: str, feature_id: str, tolerance_m: float = BOUNDARY_EXTRACT_TOLERANCE_M
) -> str:
    simplified = geom.simplify_m(geom.normalize(geometry, name=name), tolerance_m)
    mapping = simplified.__geo_interface__
    rounded = json.loads(
        json.dumps(mapping),
        parse_float=lambda value: round(float(value), BOUNDARY_COORDINATE_DIGITS),
    )
    document = {
        "type": "Feature",
        "properties": {"name": name, "source_feature_id": feature_id},
        "geometry": rounded,
    }
    return json.dumps(document, sort_keys=True, separators=(",", ":")) + "\n"


def countries(
    vendor: Path,
    destination: Path,
    mapping: dict[str, str],
    reach_m: float,
    result: UpdateResult,
    check: bool,
) -> tuple[list[str], dict[str, MultiPolygon]]:
    """Write country regions: land buffered seaward, capped by the EEZ.

    A country region is its charted land together with the water within
    `reach_m` of it — enough to close the channels between islands and their
    mainland, and to match how far the IATA layers project offshore — clipped
    to the Marine Regions EEZ + land union. The full 200-nautical-mile
    jurisdiction proved too generous (a boat in the middle of the Pacific is
    not meaningfully in any country's mesh), but it remains the ceiling: its
    bilateral maritime lines are what keep a buffer from ever claiming a
    neighbor's water. The fractal coastline lies strictly inside the region
    and vanishes, leaving smooth buffer arcs, land borders, and EEZ segments
    where neighbors are close.

    Contested areas are omitted entirely. A feature marked as an overlapping
    claim or a joint regime is skipped and named in the report, so the
    database takes no position on any dispute. If a community in a contested
    area ever wants coverage, that is a decision to make then, on its own
    terms.

    Outlying territories are keyed by their own ISO code where they have one
    (French Polynesia is PF) and by their sovereign's where they do not
    (Hawaii is US).
    """
    notes: list[str] = []
    meta, _, geometry, fields = read_ogr(f"/vsizip/{vendor / 'eez_land.shp.zip'}")
    names = list(meta["fields"])
    territory = fields[names.index("iso_ter1")]
    sovereign = fields[names.index("iso_sov1")]
    pol_types = fields[names.index("pol_type")]
    labels = fields[names.index("union")]

    kept: dict[str, list] = {}
    display: dict[str, str] = {}
    landlocked: set[str] = set()
    skipped: list[str] = []
    land = _charted_land(vendor)
    for index, wkb in enumerate(geometry):
        pol_type = str(pol_types[index])
        if pol_type not in ("Union EEZ and country", "Landlocked country"):
            skipped.append(f"{labels[index]} ({pol_type})")
            continue
        iso3 = str(territory[index] or sovereign[index] or "").upper()
        shape = from_wkb(wkb)
        # WFS axis-order sanity: EPSG:4326 over WFS 2.0 is latitude-first,
        # and a shapefile written that way has every coordinate swapped. The
        # fetch URL pins CRS84 to prevent it; this check makes sure a future
        # server or URL change fails the update instead of shipping a
        # database whose Somalia contains Geneva.
        min_lon, min_lat, max_lon, max_lat = shape.bounds
        if min_lat < -90.0 or max_lat > 90.0:
            raise ExtractError(
                f"{labels[index]}: latitude range [{min_lat:.1f}, {max_lat:.1f}] is "
                "impossible; the source geometry looks axis-swapped (WFS lat/lon order)"
            )
        code = mapping.get(iso3)
        if not code:
            notes.append(f"{labels[index]}: no ISO 3166-1 alpha-2 for {iso3 or 'unset'}, skipped")
            continue
        kept.setdefault(code, []).append(shape)
        display.setdefault(code, str(labels[index]))
        if pol_type == "Landlocked country":
            landlocked.add(code)

    unlanded: list[str] = []
    shapes: dict[str, MultiPolygon] = {}
    for code in sorted(kept):
        parts = []
        for shape in kept[code]:
            parts.extend(geom.polygonal(shape).geoms)
        jurisdiction = MultiPolygon(parts)
        if code in landlocked:
            shape = jurisdiction
        else:
            charted = _land_within(land, jurisdiction)
            if charted.is_empty:
                # No land at 50m scale — an atoll nation below the chart's
                # resolution. Keeping the whole jurisdiction is the safe
                # failure: the country stays findable, merely generous.
                unlanded.append(code)
                shape = jurisdiction
            else:
                shape = _water_reach(charted, jurisdiction, reach_m)
        shapes[code] = shape
        _write(
            destination / f"{code}.geojson",
            _boundary_document(
                shape,
                display[code],
                f"marineregions:{code}",
                tolerance_m=COUNTRY_EXTRACT_TOLERANCE_M,
            ),
            result,
            check,
        )

    notes.append(
        f"{len(kept)} country regions: charted land reaching {reach_m / 1000:.0f} km "
        f"seaward within the EEZ + land union; "
        f"{len(skipped)} contested or joint features omitted by policy"
    )
    if unlanded:
        notes.append(
            "  no charted land at 50m, whole jurisdiction kept: " + ", ".join(sorted(unlanded))
        )
    for entry in sorted(skipped):
        notes.append(f"  omitted: {entry}")
    return notes, shapes


def us_states(
    vendor: Path,
    destination: Path,
    country: MultiPolygon | None,
    reach_m: float,
    result: UpdateResult,
    check: bool,
) -> list[str]:
    """Write the 50 states plus the District of Columbia, keyed by USPS code.

    The TIGER boundary is the legal state — its islands, its internal waters,
    a few miles of territorial sea — which strands the channels between a
    state's islands and its mainland as unclaimed water: the sea between the
    Hawaiian islands is plainly Hawaiʻi. Each state therefore also gets the
    water within `reach_m` of it, clipped to the country's own water so no
    state reaches past the border, and clipped away from every state's land
    so it can never annex a neighbor. Where two states' reaches overlap —
    open water near a state line — both states cover it, the same both-sides
    answer the expansion margins give on land.
    """
    archive = vendor / "tl_2024_us_state.zip"
    meta, _, geometry, fields = read_ogr(f"/vsizip/{archive}")
    names = list(meta["fields"])
    codes = fields[names.index("STUSPS")]
    fips = fields[names.index("GEOID")]
    labels = fields[names.index("NAME")]

    rows = [
        (geom.polygonal(from_wkb(wkb)), str(code).upper(), str(geoid), str(label))
        for wkb, code, geoid, label in zip(geometry, codes, fips, labels, strict=True)
        if int(geoid) < TERRITORY_FIPS_FLOOR
    ]
    skipped = sorted(
        str(code)
        for geoid, code in zip(fips, codes, strict=True)
        if int(geoid) >= TERRITORY_FIPS_FLOOR
    )

    # The nation's water beyond every state: what a state's reach may claim.
    # States are simplified to the extract tolerance first — the mask guards
    # against annexing land, a question 50 m detail does not sharpen.
    open_water = None
    if country is not None and reach_m > 0:
        states_union = unary_union(
            [geom.simplify_m(shape, BOUNDARY_EXTRACT_TOLERANCE_M) for shape, _, _, _ in rows]
        )
        open_water = geom.polygonal(country.difference(states_union))

    for shape, code, geoid, label in rows:
        if open_water is not None:
            reached = geom.buffer_m(
                geom.polygonal(geom.simplify_m(shape, 1000.0)), reach_m
            ).intersection(open_water)
            shape = geom.polygonal(unary_union([shape, reached]))
        _write(
            destination / f"{code}.geojson",
            _boundary_document(shape, label, f"fips:{geoid}"),
            result,
            check,
        )
    reach_note = (
        f"reaching {reach_m / 1000:.0f} km into national water"
        if open_water is not None
        else "land boundaries only (no country shape)"
    )
    return [
        f"{len(rows)} US state boundaries, {reach_note}; territories excluded by policy: "
        + (", ".join(skipped) or "none")
    ]


def update(root: Path, *, check: bool = False) -> UpdateResult:
    """Run the whole distillation pass."""
    vendor = root / "vendor"
    if not vendor.is_dir():
        raise ExtractError(
            f"{vendor} does not exist. Run `regiondb-build fetch` first: `update` reads the "
            "downloaded sources, and only `fetch` may touch the network."
        )
    lock = load_lock(root / "upstream" / "lock.json")
    extracts = root / "extracts"
    result = UpdateResult()

    sites, candidates, notes = airports(vendor, lock)
    result.report.extend(notes)
    header = _provenance_header("ourairports-airports", lock)
    _write(
        extracts / "iata-locations.csv",
        _csv_text(header, IATA_LOCATIONS_COLUMNS, sites),
        result,
        check,
    )
    _write(
        extracts / "commercial-airport-candidates.csv",
        _csv_text(header, COMMERCIAL_CANDIDATE_COLUMNS, candidates),
        result,
        check,
    )

    metros = metro_codes(vendor)
    _write(
        extracts / "metro-codes.csv",
        _csv_text(_provenance_header("iata-city-codes", lock), METRO_CODE_COLUMNS, metros),
        result,
        check,
    )
    result.report.append(f"{len(metros)} metropolitan IATA codes seeded")

    reach_m = policy.load(root / "policy.yaml").maritime_reach_m

    mapping = iso3_to_iso2(vendor)
    notes, country_shapes = countries(
        vendor, extracts / "boundaries" / "country", mapping, reach_m, result, check
    )
    result.report.extend(notes)

    result.report.extend(
        us_states(
            vendor,
            extracts / "boundaries" / "us-state",
            country_shapes.get("US"),
            reach_m,
            result,
            check,
        )
    )

    return result
